# Generated by Django 4.2.6 on 2023-10-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LazoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
