# Generated by Django 4.2.6 on 2023-10-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LazoAPI', '0002_alter_product_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
