# Generated by Django 4.2.6 on 2023-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LazoAPI', '0003_product_angle1_product_angle2_product_angle3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
