# Generated by Django 4.2.6 on 2023-10-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LazoAPI', '0003_review_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
